"""Make reading_text and lecture_script nullable for Task1

Revision ID: efe280820546
Revises: a5ff904a098d
Create Date: 2025-12-13 08:30:49.213837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe280820546'
down_revision: Union[str, Sequence[str], None] = 'a5ff904a098d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('practice_sessions', 'reading_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('practice_sessions', 'lecture_script',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_sessions', 'lecture_script',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('practice_sessions', 'reading_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('practice_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
